name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Private Docker Registry
        uses: docker/login-action@v2
        with:
          registry: localhost:5000
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t handy-backend:latest .
          docker tag handy-backend:latest localhost:5000/handy-backend:latest

      - name: Push Docker image to local registry
        run: |
          docker push localhost:5000/handy-backend:latest

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}\n" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env

      - name: Log in to Docker registry on runner
        run: |
          docker login localhost:5000 -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image on runner
        run: |
          docker pull localhost:5000/handy-backend:latest

      - name: Run Docker container on runner
        run: |
          docker stop handy-be || true
          docker rm handy-be || true
          docker run -d --name handy-be -p 5000:5000 --env-file .env localhost:5000/handy-backend:latest
